################################
          #公共配置文件
################################
#__________Eureka-Server________
eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${EUREKA_SERVER_PASSWORD:eureka}@eureka-server:8061/eureka/
#________Hystrix________
#设置 thread 隔离策略的超时时间
#该超时时间需大于 ribbon 的超时时间，否则不会触发 retry
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#########################
#________Ribbon________
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
#________Rabbitmq________
spring:
  rabbitmq:
    host: rabbitmq
#________Auth-Server________
auth-service:
  hostname: auth-service
  port: 8063
  context-path: /
#________________________
copyright: ABCN.in