server:
  context-path: /uaa
  port: 8063
##########################################
spring:
  datasource:
    url: jdbc:h2:mem:hp_users
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
##########################################
management:
  security:
    enabled: false
    context-path: /admin
###########################################
eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.security.context-path}/health
    status-page-url-path: ${server.context-path}${management.security.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.security.context-path}
